Especialidades/urls.py
from django.urls import path
from . import views


app_name = "especialidades"



urlpatterns = [
    path("", views.especialidad_lista, name="lista_especialidades"),

    path("crear/", views.especialidad_crear, name="crear_especialidad"),

    path("editar/<int:pk>/", views.especialidad_editar, name="editar_especialidad"),

    path("eliminar/<int:pk>/", views.especialidad_eliminar, name="eliminar_especialidad"),


    
]

consultorio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from turnos import views as turnos_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', turnos_views.home, name='home'),

    path('turnos/', include(('turnos.urls', 'turnos'), namespace='turnos')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('esp/', include('Especialidades.urls')),
    path('aboutus/', TemplateView.as_view(template_name='aboutus.html'), name='aboutus'),

    path('admin/', admin.site.urls),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'

urlpatterns = [
    path('', views.home_redirect, name='home_redirect'),
    path('crear/', views.CrearTurnoView.as_view(), name='crear_turno'),

    # Paciente
    path('mis/', views.MisTurnosView.as_view(), name='mis_turnos'),



    # Recepcionista
    path('recepcion/all/', views.TurnosRecepcionView.as_view(), name='turnos_recepcion'),
    path('recepcion/asistencia/<int:pk>/', views.MarcarAsistenciaView.as_view(), name='marcar_asistencia'),
    path('editar/<int:pk>/', views.EditarTurnoView.as_view(), name='editar_turno'),

    # Director
    path('director/all/', views.TurnosDirectorView.as_view(), name='turnos_director'),

    # Médico
    path('medico/mis/', views.TurnosMedicoView.as_view(), name='turnos_medico'),
    path('medico/estado/<int:pk>/', views.CambiarEstadoTurnoView.as_view(), name='cambiar_estado_turno'),


    
    path('pagar/<int:turno_id>/', views.pagar_turno, name='pagar_turno'),
    path('confirmar_pago/', views.confirmar_pago, name='confirmar_pago'),

]

Especialidades/models.py
# Especialidad/models.py
from django.db import models

class Especialidad(models.Model):
    tipo = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.tipo

Especialidades/forms.py
from django import forms
from .models import Especialidad

class EspecialidadForm(forms.ModelForm):
    class Meta:
        model = Especialidad
        fields = "__all__"

Especialidades/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Especialidad
from .forms import EspecialidadForm
from django.contrib.auth.decorators import login_required


@login_required
def especialidad_lista(request):
    especialidades = Especialidad.objects.all()
    return render(request, "especialidades/lista.html", {
        "especialidades": especialidades
    })


@login_required
def especialidad_crear(request):
    if request.method == "POST":
        form = EspecialidadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("especialidades:lista_especialidades")
    else:
        form = EspecialidadForm()

    return render(request, "especialidades/crear.html", {
        "form": form
    })


@login_required
def especialidad_editar(request, pk):
    especialidad = get_object_or_404(Especialidad, pk=pk)

    if request.method == "POST":
        form = EspecialidadForm(request.POST, instance=especialidad)
        if form.is_valid():
            form.save()
            return redirect("especialidades:lista_especialidades")
    else:
        form = EspecialidadForm(instance=especialidad)

    return render(request, "especialidades/editar.html", {
        "form": form
    })

@login_required
def especialidad_eliminar(request, pk):
    especialidad = get_object_or_404(Especialidad, pk=pk)

    if request.method == "POST":
        # borrar y volver a la lista
        especialidad.delete()
        return redirect("especialidades:lista_especialidades")

    # Si es GET mostramos página de confirmación
    return render(request, "especialidades/eliminar.html", {
        "especialidad": especialidad
    })

Especialidades/templates/especialidades/crear.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Nueva Especialidad</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

Especialidades/templates/especialidades/editar.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Editar Especialidad</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Actualizar</button>
        <button class="btn btn-outline-secondary" href="esp/">Volver</button>
    </form>
</div>
{% endblock %}

Especialidades/templates/especialidades/eliminar.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">

    <h3 class="text-danger">¿Seguro que desea eliminar esta especialidad?</h3>

    <p><strong>{{ especialidad.tipo }}</strong></p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'especialidades:lista_especialidades' %}" class="btn btn-secondary">
            Cancelar
        </a>
    </form>

</div>
{% endblock %}

Especialidades/templates/especialidades/lista.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Especialidades</h2>

<div class="d-flex align-items-center gap-2 mb-3">

    <!-- Botón Crear (verde suave, estilo premium) -->
    <a href="{% url 'especialidades:crear_especialidad' %}" 
       class="btn btn-outline-success px-4 py-2 fw-semibold rounded-3">
        Crear Especialidad
    </a>

    <!-- Botón Volver (gris premium) -->
    <a href="{% url 'home' %}" 
       class="btn btn-outline-secondary px-4 py-2 fw-semibold rounded-3">
        Volver
    </a>

</div>



    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Especialidad</th>
                <th>Médico</th>
                <th>Días</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for esp in especialidades %}
            <tr>
                <td>{{ esp.id }}</td>
                <td>{{ esp.tipo }}</td>
                <td>{{ esp.id }}</td>
                <td>{{ esp.descripcion }}</td>
                <td>
                    <a href="{% url 'especialidades:editar_especialidad' esp.id %}"
                    class="btn btn-outline-secondary btn-sm me-2">
                        Editar
                    </a>

                    <a href="{% url 'especialidades:eliminar_especialidad' esp.id %}"
                    class="btn btn-outline-danger btn-sm">
                        Eliminar
                    </a>
                </td>

            </tr>
            {% empty %}
            <tr><td colspan="3">No hay especialidades.</td></tr>
            {% endfor %}
        </tbody>
    </table>



</div>
{% endblock %}